- hosts: aws
  remote_user: ubuntu
  become: yes

  tasks:
    - name: "Update cache & Full system update"
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true

    - name: "Install nano"
      apt:
        name: nano
        state: present